"""
Jinja2 HTML email templates for AI Placement Platform.
Used by NotificationService for rich HTML emails.
"""

DEADLINE_ALERT_HTML = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Deadline Alert — AI Placement Platform</title>
</head>
<body style="margin:0;padding:0;background:#0f0f1a;font-family:'Segoe UI',Arial,sans-serif;">
  <div style="max-width:600px;margin:40px auto;background:#16162a;border-radius:16px;overflow:hidden;border:1px solid #2a2a45;">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#4f46e5,#7c3aed);padding:28px 32px;">
      <p style="margin:0;color:rgba(255,255,255,0.7);font-size:12px;letter-spacing:1px;text-transform:uppercase;">AI Placement Platform</p>
      <h1 style="margin:8px 0 0;color:#fff;font-size:22px;font-weight:700;">⏰ Deadline Alert</h1>
    </div>

    <!-- Body -->
    <div style="padding:32px;">
      <p style="color:#94a3b8;margin:0 0 24px;">Hi <strong style="color:#f1f5f9;">{{ name }}</strong>,</p>
      <p style="color:#94a3b8;margin:0 0 24px;">This is a reminder about an upcoming application deadline:</p>

      <!-- Details table -->
      <table style="width:100%;border-collapse:collapse;margin-bottom:28px;border-radius:12px;overflow:hidden;">
        <tr style="background:#1e1e35;">
          <td style="padding:12px 16px;color:#64748b;font-size:13px;font-weight:600;width:35%;">Company</td>
          <td style="padding:12px 16px;color:#f1f5f9;font-size:13px;font-weight:600;">{{ company }}</td>
        </tr>
        <tr style="background:#16162a;">
          <td style="padding:12px 16px;color:#64748b;font-size:13px;font-weight:600;">Role</td>
          <td style="padding:12px 16px;color:#f1f5f9;font-size:13px;">{{ role }}</td>
        </tr>
        <tr style="background:#1e1e35;">
          <td style="padding:12px 16px;color:#64748b;font-size:13px;font-weight:600;">Deadline</td>
          <td style="padding:12px 16px;color:#ef4444;font-size:13px;font-weight:700;">{{ deadline_str }}</td>
        </tr>
        <tr style="background:#16162a;">
          <td style="padding:12px 16px;color:#64748b;font-size:13px;font-weight:600;">Priority</td>
          <td style="padding:12px 16px;color:#f59e0b;font-size:13px;font-weight:600;">{{ priority | upper }}</td>
        </tr>
      </table>

      {% if application_url %}
      <a href="{{ application_url }}"
        style="display:inline-block;background:linear-gradient(135deg,#4f46e5,#7c3aed);color:#fff;
               text-decoration:none;padding:14px 28px;border-radius:10px;font-weight:600;font-size:14px;
               margin-bottom:24px;">
        Apply Now →
      </a>
      {% endif %}

      <p style="color:#64748b;font-size:12px;margin:0;">
        This event has been automatically added to your Google Calendar with reminders.
      </p>
    </div>

    <!-- Footer -->
    <div style="padding:20px 32px;border-top:1px solid #2a2a45;text-align:center;">
      <p style="margin:0;color:#475569;font-size:11px;">
        AI Placement Platform · University Placement Cell<br>
        <a href="#" style="color:#6366f1;text-decoration:none;">Manage notification preferences</a>
      </p>
    </div>
  </div>
</body>
</html>
"""


NOTICE_BROADCAST_HTML = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Placement Notice — AI Placement Platform</title>
</head>
<body style="margin:0;padding:0;background:#0f0f1a;font-family:'Segoe UI',Arial,sans-serif;">
  <div style="max-width:600px;margin:40px auto;background:#16162a;border-radius:16px;overflow:hidden;border:1px solid #2a2a45;">

    <div style="background:linear-gradient(135deg,#0891b2,#4f46e5);padding:28px 32px;">
      <p style="margin:0;color:rgba(255,255,255,0.7);font-size:12px;letter-spacing:1px;text-transform:uppercase;">📢 Placement Notice</p>
      <h1 style="margin:8px 0 0;color:#fff;font-size:20px;font-weight:700;">{{ title }}</h1>
    </div>

    <div style="padding:32px;">
      <p style="color:#94a3b8;margin:0 0 20px;">Hi <strong style="color:#f1f5f9;">{{ name }}</strong>,</p>
      <p style="color:#94a3b8;margin:0 0 20px;">Here is the AI-generated summary of the latest placement notice:</p>

      <div style="background:#1e1e35;border-radius:12px;padding:20px;margin-bottom:24px;border-left:3px solid #6366f1;">
        {% for bullet in bullets %}
        <div style="display:flex;gap:12px;margin-bottom:14px;{% if loop.last %}margin-bottom:0;{% endif %}">
          <span style="color:#6366f1;font-weight:700;font-size:14px;flex-shrink:0;">{{ loop.index }}.</span>
          <p style="margin:0;color:#cbd5e1;font-size:13px;line-height:1.6;">{{ bullet }}</p>
        </div>
        {% endfor %}
      </div>

      <p style="color:#64748b;font-size:12px;margin:0;">
        This summary was generated by AI. Please read the full notice for complete details.
      </p>
    </div>

    <div style="padding:20px 32px;border-top:1px solid #2a2a45;text-align:center;">
      <p style="margin:0;color:#475569;font-size:11px;">
        AI Placement Platform · University Placement Cell
      </p>
    </div>
  </div>
</body>
</html>
"""


WELCOME_HTML = """
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Welcome — AI Placement Platform</title></head>
<body style="margin:0;padding:0;background:#0f0f1a;font-family:'Segoe UI',Arial,sans-serif;">
  <div style="max-width:600px;margin:40px auto;background:#16162a;border-radius:16px;overflow:hidden;border:1px solid #2a2a45;">

    <div style="background:linear-gradient(135deg,#059669,#4f46e5);padding:32px;">
      <h1 style="margin:0;color:#fff;font-size:24px;font-weight:800;">🎓 Welcome to AI Placement Platform!</h1>
    </div>

    <div style="padding:32px;">
      <p style="color:#94a3b8;margin:0 0 16px;">Hi <strong style="color:#f1f5f9;">{{ name }}</strong>, welcome aboard!</p>
      <p style="color:#94a3b8;margin:0 0 24px;">Your placement profile is now active. Here's what you've unlocked:</p>

      <div style="space-y:12px;">
        {% for feature in features %}
        <div style="display:flex;gap:12px;margin-bottom:12px;padding:12px;background:#1e1e35;border-radius:10px;">
          <span style="font-size:18px;">{{ feature.emoji }}</span>
          <div>
            <p style="margin:0;color:#f1f5f9;font-size:13px;font-weight:600;">{{ feature.title }}</p>
            <p style="margin:4px 0 0;color:#64748b;font-size:12px;">{{ feature.desc }}</p>
          </div>
        </div>
        {% endfor %}
      </div>

      <a href="{{ dashboard_url }}"
        style="display:inline-block;margin-top:24px;background:#4f46e5;color:#fff;
               text-decoration:none;padding:14px 28px;border-radius:10px;font-weight:600;font-size:14px;">
        Go to Dashboard →
      </a>
    </div>

    <div style="padding:20px 32px;border-top:1px solid #2a2a45;text-align:center;">
      <p style="margin:0;color:#475569;font-size:11px;">AI Placement Platform · University Placement Cell</p>
    </div>
  </div>
</body>
</html>
"""


def render_deadline_alert(
    name: str,
    company: str,
    role: str,
    deadline_str: str,
    priority: str,
    application_url: str = "",
) -> str:
    from jinja2 import Template
    return Template(DEADLINE_ALERT_HTML).render(
        name=name, company=company, role=role,
        deadline_str=deadline_str, priority=priority,
        application_url=application_url,
    )


def render_notice_broadcast(name: str, title: str, bullets: list) -> str:
    from jinja2 import Template
    return Template(NOTICE_BROADCAST_HTML).render(name=name, title=title, bullets=bullets)


def render_welcome(name: str, dashboard_url: str = "http://localhost:3000/dashboard") -> str:
    from jinja2 import Template
    features = [
        {"emoji": "📱", "title": "WhatsApp Alerts",    "desc": "Deadline reminders delivered in < 30 seconds"},
        {"emoji": "📅", "title": "Calendar Sync",      "desc": "Auto-creates Google Calendar events for all deadlines"},
        {"emoji": "🤖", "title": "AI Job Matching",    "desc": "Smart job recommendations based on your skills"},
        {"emoji": "📊", "title": "Placement Score",    "desc": "Dynamic readiness score updated in real time"},
    ]
    return Template(WELCOME_HTML).render(name=name, dashboard_url=dashboard_url, features=features)
